name: treqsy_platform

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_riverpod: ^2.4.0
  shared_preferences: ^2.5.3
  jwt_decoder: ^2.0.1
  fl_chart: ^0.64.0

environment:
  sdk: ">=3.0.0 <4.0.0" 