name: livestream_platform
description: "A comprehensive live streaming platform with multi-role support, real-time interactions, and monetization features."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.4
  flutter_animate: ^4.2.0
  lottie: ^3.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  pull_to_refresh: ^2.0.0
  flutter_switch: ^0.3.2
  country_code_picker: ^2.0.2
  image_picker: ^1.0.7
  image_cropper: ^6.0.1
  image: ^4.1.7
  file_picker: ^6.1.2
  path_provider: ^2.1.2
  path: ^1.8.3
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.2
  connectivity_plus: ^5.0.2
  flutter_dotenv: ^5.1.0
  intl_phone_field: ^3.1.0
  pin_code_fields: ^8.0.2
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  uuid: ^4.2.2
  equatable: ^2.0.5
  get_it: ^7.6.7
  provider: ^6.1.1
  flutter_bloc: ^8.1.4
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  logger: ^2.0.2
  web_socket_channel: ^2.4.5
  web_socket_io: ^1.0.2
  permission_handler: ^11.2.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_local_notifications: ^16.3.0
  timeago: ^3.6.3
  flutter_facebook_auth: ^5.0.10
  google_sign_in: ^6.1.7
  sign_in_with_apple: ^5.0.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.7.2
  firebase_crashlytics: ^3.1.2
  firebase_performance: ^0.9.2+1
  firebase_dynamic_links: ^5.9.1
  firebase_remote_config: ^4.2.4
  in_app_purchase: ^3.1.13
  in_app_review: ^2.0.8
  upgrader: ^7.4.1
  sentry_flutter: ^7.15.0
  flutter_web_plugins: any
  http: ^1.1.2
  http_parser: ^4.0.2
  crypto: ^3.0.3
  intl_phone_number_input: ^0.8.1
  flutter_contacts: ^1.1.7+1
  flutter_contacts_plus: ^1.0.6
  flutter_contacts_plus_platform_interface: ^1.0.6
  flutter_contacts_plus_android: ^1.0.6
  flutter_contacts_plus_ios: ^1.0.6
  flutter_contacts_plus_web: ^1.0.6
  flutter_contacts_plus_linux: ^1.0.6
  flutter_contacts_plus_macos: ^1.0.6
  flutter_contacts_plus_windows: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  flutter_oss_licenses: ^3.0.1
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.3
  test: ^1.24.9
  test_coverage: ^0.5.1
  flutter_driver:
    sdk: flutter
  flutter_gen_runner: ^5.3.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
    - assets/translations/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

# Flutter launcher icons configuration
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_icon_web.png"
  windows:
    generate: true
    image_path: "assets/images/app_icon_windows.png"
  macos:
    generate: true
    image_path: "assets/images/app_icon_macos.png"
  linux:
    generate: true
    image_path: "assets/images/app_icon_linux.png"

# Flutter native splash screen configuration
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo.png
    icon_background_color: "#FFFFFF"
  web:
    image: assets/images/splash_logo.png
    background_color: "#FFFFFF"
  windows:
    image: assets/images/splash_logo.png
    background_color: "#FFFFFF"
  macos:
    image: assets/images/splash_logo.png
    background_color: "#FFFFFF"
  linux:
    image: assets/images/splash_logo.png
    background_color: "#FFFFFF"
