apiVersion: apps/v1
kind: Deployment
metadata:
  name: livestream-api
  labels:
    app: livestream-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: livestream-api
  template:
    metadata:
      labels:
        app: livestream-api
    spec:
      containers:
      - name: livestream-api
        image: ${DOCKER_REGISTRY}/livestream-api:${VERSION}
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: livestream-secrets
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: livestream-api
spec:
  selector:
    app: livestream-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
